// @ts-nocheck
// Auto-generated by scripts/build-tailwind-showcase.mjs — do not edit manually
export type TailwindShowcaseEntry = {
  id: string;
  category: string;
  label: string;
  Component: React.ComponentType;
};

import type React from "react";

import ElementsBannersN01WithButton from "./blocks/elements/banners/01-with-button";
import ElementsBannersN02OnDark from "./blocks/elements/banners/02-on-dark";
import ElementsBannersN03OnBrand from "./blocks/elements/banners/03-on-brand";
import ElementsBannersN04WithBackgroundGlow from "./blocks/elements/banners/04-with-background-glow";
import ElementsBannersN05WithLink from "./blocks/elements/banners/05-with-link";
import ElementsBannersN06LeftAligned from "./blocks/elements/banners/06-left-aligned";
import ElementsBannersN07BottomAligned from "./blocks/elements/banners/07-bottom-aligned";
import ElementsBannersN08FloatingAtBottom from "./blocks/elements/banners/08-floating-at-bottom";
import ElementsBannersN09FloatingAtBottomCentered from "./blocks/elements/banners/09-floating-at-bottom-centered";
import ElementsBannersN10PrivacyNoticeRightAligned from "./blocks/elements/banners/10-privacy-notice-right-aligned";
import ElementsBannersN11PrivacyNoticeCentered from "./blocks/elements/banners/11-privacy-notice-centered";
import ElementsBannersN12PrivacyNoticeLeftAligned from "./blocks/elements/banners/12-privacy-notice-left-aligned";
import ElementsBannersN13PrivacyNoticeFullWidth from "./blocks/elements/banners/13-privacy-notice-full-width";
import ElementsFlyoutMenusN01StackedWithFooterActions from "./blocks/elements/flyout-menus/01-stacked-with-footer-actions";
import ElementsFlyoutMenusN02FullWidthTwoColumns from "./blocks/elements/flyout-menus/02-full-width-two-columns";
import ElementsFlyoutMenusN03StackedWithFooterList from "./blocks/elements/flyout-menus/03-stacked-with-footer-list";
import ElementsFlyoutMenusN04FullWidth from "./blocks/elements/flyout-menus/04-full-width";
import ElementsFlyoutMenusN05SimpleWithDescriptions from "./blocks/elements/flyout-menus/05-simple-with-descriptions";
import ElementsFlyoutMenusN06TwoColumn from "./blocks/elements/flyout-menus/06-two-column";
import ElementsFlyoutMenusN07Simple from "./blocks/elements/flyout-menus/07-simple";
import ElementsHeadersN01WithStackedFlyoutMenu from "./blocks/elements/headers/01-with-stacked-flyout-menu";
import ElementsHeadersN02Constrained from "./blocks/elements/headers/02-constrained";
import ElementsHeadersN04OnBrandBackground from "./blocks/elements/headers/04-on-brand-background";
import ElementsHeadersN05WithFullWidthFlyoutMenu from "./blocks/elements/headers/05-with-full-width-flyout-menu";
import ElementsHeadersN06FullWidth from "./blocks/elements/headers/06-full-width";
import ElementsHeadersN07WithCallToAction from "./blocks/elements/headers/07-with-call-to-action";
import ElementsHeadersN08WithMultipleFlyoutMenus from "./blocks/elements/headers/08-with-multiple-flyout-menus";
import ElementsHeadersN09WithIconsInMobileMenu from "./blocks/elements/headers/09-with-icons-in-mobile-menu";
import ElementsHeadersN10WithLeftAlignedNav from "./blocks/elements/headers/10-with-left-aligned-nav";
import ElementsHeadersN11WithRightAlignedNav from "./blocks/elements/headers/11-with-right-aligned-nav";
import ElementsHeadersN12WithCenteredLogo from "./blocks/elements/headers/12-with-centered-logo";
import FeedbackN404PagesN01Simple from "./blocks/feedback/404-pages/01-simple";
import FeedbackN404PagesN02SplitWithImage from "./blocks/feedback/404-pages/02-split-with-image";
import FeedbackN404PagesN03WithPopularPages from "./blocks/feedback/404-pages/03-with-popular-pages";
import FeedbackN404PagesN05WithBackgroundImage from "./blocks/feedback/404-pages/05-with-background-image";
import FeedbackN404PagesN06WithNavbarAndFooter from "./blocks/feedback/404-pages/06-with-navbar-and-footer";
import PageExamplesAboutPagesN01WithImageTiles from "./blocks/page-examples/about-pages/01-with-image-tiles";
import PageExamplesAboutPagesN02WithTimelineAndStats from "./blocks/page-examples/about-pages/02-with-timeline-and-stats";
import PageExamplesAboutPagesN03WithTwoColumnDescription from "./blocks/page-examples/about-pages/03-with-two-column-description";
import PageExamplesLandingPagesN01WithScreenshotsAndStats from "./blocks/page-examples/landing-pages/01-with-screenshots-and-stats";
import PageExamplesLandingPagesN02WithLargeScreenshotAndTestimonial from "./blocks/page-examples/landing-pages/02-with-large-screenshot-and-testimonial";
import PageExamplesLandingPagesN03WithBackgroundImageHeroAndPricingSection from "./blocks/page-examples/landing-pages/03-with-background-image-hero-and-pricing-section";
import PageExamplesLandingPagesN04WithMobileScreenshotAndTestimonialsGrid from "./blocks/page-examples/landing-pages/04-with-mobile-screenshot-and-testimonials-grid";
import PageExamplesPricingPagesN01WithFourTiers from "./blocks/page-examples/pricing-pages/01-with-four-tiers";
import PageExamplesPricingPagesN02WithComparisonTable from "./blocks/page-examples/pricing-pages/02-with-comparison-table";
import PageExamplesPricingPagesN03WithThreeTiersAndTestimonials from "./blocks/page-examples/pricing-pages/03-with-three-tiers-and-testimonials";
import SectionsBentoGridsN01ThreeColumnBentoGrid from "./blocks/sections/bento-grids/01-three-column-bento-grid";
import SectionsBentoGridsN02TwoRowBentoGrid from "./blocks/sections/bento-grids/02-two-row-bento-grid";
import SectionsBentoGridsN03TwoRowBentoGridWithThreeColumnSecondRow from "./blocks/sections/bento-grids/03-two-row-bento-grid-with-three-column-second-row";
import SectionsBlogSectionsN01ThreeColumn from "./blocks/sections/blog-sections/01-three-column";
import SectionsBlogSectionsN02ThreeColumnWithImages from "./blocks/sections/blog-sections/02-three-column-with-images";
import SectionsBlogSectionsN03ThreeColumnWithBackgroundImages from "./blocks/sections/blog-sections/03-three-column-with-background-images";
import SectionsBlogSectionsN04SingleColumn from "./blocks/sections/blog-sections/04-single-column";
import SectionsBlogSectionsN05SingleColumnWithImages from "./blocks/sections/blog-sections/05-single-column-with-images";
import SectionsBlogSectionsN06WithFeaturedPost from "./blocks/sections/blog-sections/06-with-featured-post";
import SectionsBlogSectionsN07WithPhotoAndList from "./blocks/sections/blog-sections/07-with-photo-and-list";
import SectionsContactSectionsN01Centered from "./blocks/sections/contact-sections/01-centered";
import SectionsContactSectionsN02SideBySideGrid from "./blocks/sections/contact-sections/02-side-by-side-grid";
import SectionsContactSectionsN03SplitWithPattern from "./blocks/sections/contact-sections/03-split-with-pattern";
import SectionsContactSectionsN05SimpleFourColumn from "./blocks/sections/contact-sections/05-simple-four-column";
import SectionsContactSectionsN06SimpleCentered from "./blocks/sections/contact-sections/06-simple-centered";
import SectionsContactSectionsN07WithTestimonial from "./blocks/sections/contact-sections/07-with-testimonial";
import SectionsContactSectionsN08SplitWithImage from "./blocks/sections/contact-sections/08-split-with-image";
import SectionsContentSectionsN01WithStickyProductScreenshot from "./blocks/sections/content-sections/01-with-sticky-product-screenshot";
import SectionsContentSectionsN02WithTestimonial from "./blocks/sections/content-sections/02-with-testimonial";
import SectionsContentSectionsN03WithImageTiles from "./blocks/sections/content-sections/03-with-image-tiles";
import SectionsContentSectionsN04TwoColumnsWithScreenshot from "./blocks/sections/content-sections/04-two-columns-with-screenshot";
import SectionsContentSectionsN05WithTestimonialAndStats from "./blocks/sections/content-sections/05-with-testimonial-and-stats";
import SectionsContentSectionsN06SplitWithImage from "./blocks/sections/content-sections/06-split-with-image";
import SectionsContentSectionsN07Centered from "./blocks/sections/content-sections/07-centered";
import SectionsCtaSectionsN01DarkPanelWithAppScreenshot from "./blocks/sections/cta-sections/01-dark-panel-with-app-screenshot";
import SectionsCtaSectionsN02SimpleStacked from "./blocks/sections/cta-sections/02-simple-stacked";
import SectionsCtaSectionsN03CenteredOnDarkPanel from "./blocks/sections/cta-sections/03-centered-on-dark-panel";
import SectionsCtaSectionsN04SimpleCentered from "./blocks/sections/cta-sections/04-simple-centered";
import SectionsCtaSectionsN05SimpleCenteredWithGradient from "./blocks/sections/cta-sections/05-simple-centered-with-gradient";
import SectionsCtaSectionsN06SimpleCenteredOnBrand from "./blocks/sections/cta-sections/06-simple-centered-on-brand";
import SectionsCtaSectionsN07SimpleJustified from "./blocks/sections/cta-sections/07-simple-justified";
import SectionsCtaSectionsN08SimpleJustifiedOnSubtleBrand from "./blocks/sections/cta-sections/08-simple-justified-on-subtle-brand";
import SectionsCtaSectionsN09SplitWithImage from "./blocks/sections/cta-sections/09-split-with-image";
import SectionsCtaSectionsN10TwoColumnsWithPhoto from "./blocks/sections/cta-sections/10-two-columns-with-photo";
import SectionsCtaSectionsN11WithImageTiles from "./blocks/sections/cta-sections/11-with-image-tiles";
import SectionsFaqSectionsN01OffsetWithSupportingText from "./blocks/sections/faq-sections/01-offset-with-supporting-text";
import SectionsFaqSectionsN02CenteredAccordion from "./blocks/sections/faq-sections/02-centered-accordion";
import SectionsFaqSectionsN04SideBySide from "./blocks/sections/faq-sections/04-side-by-side";
import SectionsFaqSectionsN05ThreeColumns from "./blocks/sections/faq-sections/05-three-columns";
import SectionsFaqSectionsN07ThreeColumnsWithCenteredIntroduction from "./blocks/sections/faq-sections/07-three-columns-with-centered-introduction";
import SectionsFaqSectionsN08TwoColumns from "./blocks/sections/faq-sections/08-two-columns";
import SectionsFaqSectionsN10TwoColumnsWithCenteredIntroduction from "./blocks/sections/faq-sections/10-two-columns-with-centered-introduction";
import SectionsFeatureSectionsN01WithProductScreenshot from "./blocks/sections/feature-sections/01.with-product-screenshot";
import SectionsFeatureSectionsN03WithLargeScreenshot from "./blocks/sections/feature-sections/03.with-large-screenshot";
import SectionsFeatureSectionsN05WithLargeBorderedScreenshot from "./blocks/sections/feature-sections/05.with-large-bordered-screenshot";
import SectionsFeatureSectionsN07SimpleThreeColumnWithSmallIcons from "./blocks/sections/feature-sections/07.simple-three-column-with-small-icons";
import SectionsFeatureSectionsN09WithProductScreenshotOnLeft from "./blocks/sections/feature-sections/09.with-product-screenshot-on-left";
import SectionsFeatureSectionsN10SimpleThreeColumnWithLargeIcons from "./blocks/sections/feature-sections/10.simple-three-column-with-large-icons";
import SectionsFeatureSectionsN12ContainedInPanel from "./blocks/sections/feature-sections/12.contained-in-panel";
import SectionsFeatureSectionsN13WithProductScreenshotPanel from "./blocks/sections/feature-sections/13.with-product-screenshot-panel";
import SectionsFeatureSectionsN14WithTestimonial from "./blocks/sections/feature-sections/14.with-testimonial";
import SectionsFeatureSectionsN15Offset2x2Grid from "./blocks/sections/feature-sections/15.offset-2x2-grid";
import SectionsFeatureSectionsN16WithCodeExamplePanel from "./blocks/sections/feature-sections/16.with-code-example-panel";
import SectionsFeatureSectionsN17OffsetWithFeatureList from "./blocks/sections/feature-sections/17.offset-with-feature-list";
import SectionsFeatureSectionsN18Simple from "./blocks/sections/feature-sections/18.simple";
import SectionsFeatureSectionsN19Centered2x2Grid from "./blocks/sections/feature-sections/19.centered-2x2-grid";
import SectionsFeatureSectionsN20Simple3x2Grid from "./blocks/sections/feature-sections/20.simple-3x2-grid";
import SectionsFootersN02N4ColumnWithCompanyMission from "./blocks/sections/footers/02-4-column-with-company-mission";
import SectionsFootersN04N4ColumnWithCallToAction from "./blocks/sections/footers/04-4-column-with-call-to-action";
import SectionsFootersN06N4ColumnSimple from "./blocks/sections/footers/06-4-column-simple";
import SectionsFootersN08N4ColumnWithNewsletter from "./blocks/sections/footers/08-4-column-with-newsletter";
import SectionsFootersN10N4ColumnWithNewsletterBelow from "./blocks/sections/footers/10-4-column-with-newsletter-below";
import SectionsFootersN12SimpleCentered from "./blocks/sections/footers/12-simple-centered";
import SectionsFootersN14SimpleWithSocialLinks from "./blocks/sections/footers/14-simple-with-social-links";
import SectionsHeaderN01WithStats from "./blocks/sections/header/01-with-stats";
import SectionsHeaderN02Centered from "./blocks/sections/header/02-centered";
import SectionsHeaderN03CenteredWithEyebrow from "./blocks/sections/header/03-centered-with-eyebrow";
import SectionsHeaderN04WithCards from "./blocks/sections/header/04-with-cards";
import SectionsHeaderN05Simple from "./blocks/sections/header/05-simple";
import SectionsHeaderN06SimpleWithEyebrow from "./blocks/sections/header/06-simple-with-eyebrow";
import SectionsHeaderN07SimpleWithBackgroundImage from "./blocks/sections/header/07-simple-with-background-image";
import SectionsHeaderN08CenteredWithBackgroundImage from "./blocks/sections/header/08-centered-with-background-image";
import SectionsHeroesN01SimpleCentered from "./blocks/sections/heroes/01-simple-centered";
import SectionsHeroesN02SplitWithScreenshot from "./blocks/sections/heroes/02-split-with-screenshot";
import SectionsHeroesN03SplitWithBorderedScreenshot from "./blocks/sections/heroes/03-split-with-bordered-screenshot";
import SectionsHeroesN04SplitWithCodeExample from "./blocks/sections/heroes/04-split-with-code-example";
import SectionsHeroesN05SimpleCenteredWithBackgroundImage from "./blocks/sections/heroes/05-simple-centered-with-background-image";
import SectionsHeroesN06WithBorderedAppScreenshot from "./blocks/sections/heroes/06-with-bordered-app-screenshot";
import SectionsHeroesN07WithAppScreenshot from "./blocks/sections/heroes/07-with-app-screenshot";
import SectionsHeroesN08WithPhoneMockup from "./blocks/sections/heroes/08-with-phone-mockup";
import SectionsHeroesN09SplitWithImage from "./blocks/sections/heroes/09-split-with-image";
import SectionsHeroesN10WithAngledImageOnRight from "./blocks/sections/heroes/10-with-angled-image-on-right";
import SectionsHeroesN11WithImageTiles from "./blocks/sections/heroes/11-with-image-tiles";
import SectionsHeroesN12WithOffsetImage from "./blocks/sections/heroes/12-with-offset-image";
import SectionsLogoCloudsN01SimpleWithHeading from "./blocks/sections/logo-clouds/01-simple-with-heading";
import SectionsLogoCloudsN03SimpleWithCallToAction from "./blocks/sections/logo-clouds/03-simple-with-call-to-action";
import SectionsLogoCloudsN05SimpleLeftAligned from "./blocks/sections/logo-clouds/05-simple-left-aligned";
import SectionsLogoCloudsN07SplitWithLogosOnRight from "./blocks/sections/logo-clouds/07-split-with-logos-on-right";
import SectionsLogoCloudsN09Simple from "./blocks/sections/logo-clouds/09-simple";
import SectionsLogoCloudsN11Grid from "./blocks/sections/logo-clouds/11-grid";
import SectionsNewsletterSectionsN01SideBySideWithDetails from "./blocks/sections/newsletter-sections/01-side-by-side-with-details";
import SectionsNewsletterSectionsN02SimpleSideBySide from "./blocks/sections/newsletter-sections/02-simple-side-by-side";
import SectionsNewsletterSectionsN04SimpleSideBySideOnBrand from "./blocks/sections/newsletter-sections/04-simple-side-by-side-on-brand";
import SectionsNewsletterSectionsN05SimpleStacked from "./blocks/sections/newsletter-sections/05-simple-stacked";
import SectionsNewsletterSectionsN06CenteredCard from "./blocks/sections/newsletter-sections/06-centered-card";
import SectionsNewsletterSectionsN07SideBySideOnCard from "./blocks/sections/newsletter-sections/07-side-by-side-on-card";
import SectionsPricingN01TwoTiersWithEmphasizedRightTier from "./blocks/sections/pricing/01-two-tiers-with-emphasized-right-tier";
import SectionsPricingN02TwoTiersWithEmphasizedLeftTier from "./blocks/sections/pricing/02-two-tiers-with-emphasized-left-tier";
import SectionsPricingN03ThreeTiersWithLogosAndFeatureComparison from "./blocks/sections/pricing/03-three-tiers-with-logos-and-feature-comparison";
import SectionsPricingN04TwoTiersWithExtraTier from "./blocks/sections/pricing/04-two-tiers-with-extra-tier";
import SectionsPricingN05SinglePriceWithDetails from "./blocks/sections/pricing/05-single-price-with-details";
import SectionsPricingN06ThreeTiers from "./blocks/sections/pricing/06-three-tiers";
import SectionsPricingN07ThreeTiersWithDividers from "./blocks/sections/pricing/07-three-tiers-with-dividers";
import SectionsPricingN08ThreeTiersWithEmphasizedTier from "./blocks/sections/pricing/08-three-tiers-with-emphasized-tier";
import SectionsPricingN09ThreeTiersWithToggle from "./blocks/sections/pricing/09-three-tiers-with-toggle";
import SectionsPricingN11FourTiersWithToggle from "./blocks/sections/pricing/11-four-tiers-with-toggle";
import SectionsPricingN12WithComparisonTable from "./blocks/sections/pricing/12-with-comparison-table";
import SectionsPricingN14ThreeTiersWithFeatureComparison from "./blocks/sections/pricing/14-three-tiers-with-feature-comparison";
import SectionsStatsSectionsN01Simple from "./blocks/sections/stats-sections/01-simple";
import SectionsStatsSectionsN03SimpleGrid from "./blocks/sections/stats-sections/03-simple-grid";
import SectionsStatsSectionsN05WithBackgroundImage from "./blocks/sections/stats-sections/05-with-background-image";
import SectionsStatsSectionsN06SplitWithImage from "./blocks/sections/stats-sections/06-split-with-image";
import SectionsStatsSectionsN07Timeline from "./blocks/sections/stats-sections/07-timeline";
import SectionsStatsSectionsN08Stepped from "./blocks/sections/stats-sections/08-stepped";
import SectionsStatsSectionsN09TwoColumnDescription from "./blocks/sections/stats-sections/09-two-column-description";
import SectionsStatsSectionsN10WithDescription from "./blocks/sections/stats-sections/10-with-description";
import SectionsTeamSectionsN01SmallImages from "./blocks/sections/team-sections/01-small-images";
import SectionsTeamSectionsN02LargeImages from "./blocks/sections/team-sections/02-large-images";
import SectionsTeamSectionsN03GridWithRoundImages from "./blocks/sections/team-sections/03-grid-with-round-images";
import SectionsTeamSectionsN04LargeGridWithCards from "./blocks/sections/team-sections/04-large-grid-with-cards";
import SectionsTeamSectionsN05WithImageAndShortParagraph from "./blocks/sections/team-sections/05-with-image-and-short-paragraph";
import SectionsTeamSectionsN06WithVerticalImages from "./blocks/sections/team-sections/06-with-vertical-images";
import SectionsTeamSectionsN07WithVerticalImagesFullWidth from "./blocks/sections/team-sections/07-with-vertical-images-full-width";
import SectionsTeamSectionsN08GridWithLargeRoundImages from "./blocks/sections/team-sections/08-grid-with-large-round-images";
import SectionsTeamSectionsN09MediumImages from "./blocks/sections/team-sections/09-medium-images";
import SectionsTestimonialsN02SimpleCentered from "./blocks/sections/testimonials/02-simple-centered";
import SectionsTestimonialsN03WithLargeAvatar from "./blocks/sections/testimonials/03-with-large-avatar";
import SectionsTestimonialsN04WithOverlappingImage from "./blocks/sections/testimonials/04-with-overlapping-image";
import SectionsTestimonialsN05WithBackgroundImage from "./blocks/sections/testimonials/05-with-background-image";
import SectionsTestimonialsN06SideBySide from "./blocks/sections/testimonials/06-side-by-side";
import SectionsTestimonialsN08WithStarRating from "./blocks/sections/testimonials/08-with-star-rating";
import SectionsTestimonialsN09Grid from "./blocks/sections/testimonials/09-grid";
import SectionsTestimonialsN10SubtleGrid from "./blocks/sections/testimonials/10-subtle-grid";

export const tailwindShowcaseRegistry: TailwindShowcaseEntry[] = [
  { id: "elements-banners-01-with-button", category: "elements / banners", label: "01-with-button", Component: ElementsBannersN01WithButton },
  { id: "elements-banners-02-on-dark", category: "elements / banners", label: "02-on-dark", Component: ElementsBannersN02OnDark },
  { id: "elements-banners-03-on-brand", category: "elements / banners", label: "03-on-brand", Component: ElementsBannersN03OnBrand },
  { id: "elements-banners-04-with-background-glow", category: "elements / banners", label: "04-with-background-glow", Component: ElementsBannersN04WithBackgroundGlow },
  { id: "elements-banners-05-with-link", category: "elements / banners", label: "05-with-link", Component: ElementsBannersN05WithLink },
  { id: "elements-banners-06-left-aligned", category: "elements / banners", label: "06-left-aligned", Component: ElementsBannersN06LeftAligned },
  { id: "elements-banners-07-bottom-aligned", category: "elements / banners", label: "07-bottom-aligned", Component: ElementsBannersN07BottomAligned },
  { id: "elements-banners-08-floating-at-bottom", category: "elements / banners", label: "08-floating-at-bottom", Component: ElementsBannersN08FloatingAtBottom },
  { id: "elements-banners-09-floating-at-bottom-centered", category: "elements / banners", label: "09-floating-at-bottom-centered", Component: ElementsBannersN09FloatingAtBottomCentered },
  { id: "elements-banners-10-privacy-notice-right-aligned", category: "elements / banners", label: "10-privacy-notice-right-aligned", Component: ElementsBannersN10PrivacyNoticeRightAligned },
  { id: "elements-banners-11-privacy-notice-centered", category: "elements / banners", label: "11-privacy-notice-centered", Component: ElementsBannersN11PrivacyNoticeCentered },
  { id: "elements-banners-12-privacy-notice-left-aligned", category: "elements / banners", label: "12-privacy-notice-left-aligned", Component: ElementsBannersN12PrivacyNoticeLeftAligned },
  { id: "elements-banners-13-privacy-notice-full-width", category: "elements / banners", label: "13-privacy-notice-full-width", Component: ElementsBannersN13PrivacyNoticeFullWidth },
  { id: "elements-flyout-menus-01-stacked-with-footer-actions", category: "elements / flyout-menus", label: "01-stacked-with-footer-actions", Component: ElementsFlyoutMenusN01StackedWithFooterActions },
  { id: "elements-flyout-menus-02-full-width-two-columns", category: "elements / flyout-menus", label: "02-full-width-two-columns", Component: ElementsFlyoutMenusN02FullWidthTwoColumns },
  { id: "elements-flyout-menus-03-stacked-with-footer-list", category: "elements / flyout-menus", label: "03-stacked-with-footer-list", Component: ElementsFlyoutMenusN03StackedWithFooterList },
  { id: "elements-flyout-menus-04-full-width", category: "elements / flyout-menus", label: "04-full-width", Component: ElementsFlyoutMenusN04FullWidth },
  { id: "elements-flyout-menus-05-simple-with-descriptions", category: "elements / flyout-menus", label: "05-simple-with-descriptions", Component: ElementsFlyoutMenusN05SimpleWithDescriptions },
  { id: "elements-flyout-menus-06-two-column", category: "elements / flyout-menus", label: "06-two-column", Component: ElementsFlyoutMenusN06TwoColumn },
  { id: "elements-flyout-menus-07-simple", category: "elements / flyout-menus", label: "07-simple", Component: ElementsFlyoutMenusN07Simple },
  { id: "elements-headers-01-with-stacked-flyout-menu", category: "elements / headers", label: "01-with-stacked-flyout-menu", Component: ElementsHeadersN01WithStackedFlyoutMenu },
  { id: "elements-headers-02-constrained", category: "elements / headers", label: "02-constrained", Component: ElementsHeadersN02Constrained },
  { id: "elements-headers-04-on-brand-background", category: "elements / headers", label: "04-on-brand-background", Component: ElementsHeadersN04OnBrandBackground },
  { id: "elements-headers-05-with-full-width-flyout-menu", category: "elements / headers", label: "05-with-full-width-flyout-menu", Component: ElementsHeadersN05WithFullWidthFlyoutMenu },
  { id: "elements-headers-06-full-width", category: "elements / headers", label: "06-full-width", Component: ElementsHeadersN06FullWidth },
  { id: "elements-headers-07-with-call-to-action", category: "elements / headers", label: "07-with-call-to-action", Component: ElementsHeadersN07WithCallToAction },
  { id: "elements-headers-08-with-multiple-flyout-menus", category: "elements / headers", label: "08-with-multiple-flyout-menus", Component: ElementsHeadersN08WithMultipleFlyoutMenus },
  { id: "elements-headers-09-with-icons-in-mobile-menu", category: "elements / headers", label: "09-with-icons-in-mobile-menu", Component: ElementsHeadersN09WithIconsInMobileMenu },
  { id: "elements-headers-10-with-left-aligned-nav", category: "elements / headers", label: "10-with-left-aligned-nav", Component: ElementsHeadersN10WithLeftAlignedNav },
  { id: "elements-headers-11-with-right-aligned-nav", category: "elements / headers", label: "11-with-right-aligned-nav", Component: ElementsHeadersN11WithRightAlignedNav },
  { id: "elements-headers-12-with-centered-logo", category: "elements / headers", label: "12-with-centered-logo", Component: ElementsHeadersN12WithCenteredLogo },
  { id: "feedback-404-pages-01-simple", category: "feedback / 404-pages", label: "01-simple", Component: FeedbackN404PagesN01Simple },
  { id: "feedback-404-pages-02-split-with-image", category: "feedback / 404-pages", label: "02-split-with-image", Component: FeedbackN404PagesN02SplitWithImage },
  { id: "feedback-404-pages-03-with-popular-pages", category: "feedback / 404-pages", label: "03-with-popular-pages", Component: FeedbackN404PagesN03WithPopularPages },
  { id: "feedback-404-pages-05-with-background-image", category: "feedback / 404-pages", label: "05-with-background-image", Component: FeedbackN404PagesN05WithBackgroundImage },
  { id: "feedback-404-pages-06-with-navbar-and-footer", category: "feedback / 404-pages", label: "06-with-navbar-and-footer", Component: FeedbackN404PagesN06WithNavbarAndFooter },
  { id: "page-examples-about-pages-01-with-image-tiles", category: "page-examples / about-pages", label: "01-with-image-tiles", Component: PageExamplesAboutPagesN01WithImageTiles },
  { id: "page-examples-about-pages-02-with-timeline-and-stats", category: "page-examples / about-pages", label: "02-with-timeline-and-stats", Component: PageExamplesAboutPagesN02WithTimelineAndStats },
  { id: "page-examples-about-pages-03-with-two-column-description", category: "page-examples / about-pages", label: "03-with-two-column-description", Component: PageExamplesAboutPagesN03WithTwoColumnDescription },
  { id: "page-examples-landing-pages-01-with-screenshots-and-stats", category: "page-examples / landing-pages", label: "01-with-screenshots-and-stats", Component: PageExamplesLandingPagesN01WithScreenshotsAndStats },
  { id: "page-examples-landing-pages-02-with-large-screenshot-and-testimonial", category: "page-examples / landing-pages", label: "02-with-large-screenshot-and-testimonial", Component: PageExamplesLandingPagesN02WithLargeScreenshotAndTestimonial },
  { id: "page-examples-landing-pages-03-with-background-image-hero-and-pricing-section", category: "page-examples / landing-pages", label: "03-with-background-image-hero-and-pricing-section", Component: PageExamplesLandingPagesN03WithBackgroundImageHeroAndPricingSection },
  { id: "page-examples-landing-pages-04-with-mobile-screenshot-and-testimonials-grid", category: "page-examples / landing-pages", label: "04-with-mobile-screenshot-and-testimonials-grid", Component: PageExamplesLandingPagesN04WithMobileScreenshotAndTestimonialsGrid },
  { id: "page-examples-pricing-pages-01-with-four-tiers", category: "page-examples / pricing-pages", label: "01-with-four-tiers", Component: PageExamplesPricingPagesN01WithFourTiers },
  { id: "page-examples-pricing-pages-02-with-comparison-table", category: "page-examples / pricing-pages", label: "02-with-comparison-table", Component: PageExamplesPricingPagesN02WithComparisonTable },
  { id: "page-examples-pricing-pages-03-with-three-tiers-and-testimonials", category: "page-examples / pricing-pages", label: "03-with-three-tiers-and-testimonials", Component: PageExamplesPricingPagesN03WithThreeTiersAndTestimonials },
  { id: "sections-bento-grids-01-three-column-bento-grid", category: "sections / bento-grids", label: "01-three-column-bento-grid", Component: SectionsBentoGridsN01ThreeColumnBentoGrid },
  { id: "sections-bento-grids-02-two-row-bento-grid", category: "sections / bento-grids", label: "02-two-row-bento-grid", Component: SectionsBentoGridsN02TwoRowBentoGrid },
  { id: "sections-bento-grids-03-two-row-bento-grid-with-three-column-second-row", category: "sections / bento-grids", label: "03-two-row-bento-grid-with-three-column-second-row", Component: SectionsBentoGridsN03TwoRowBentoGridWithThreeColumnSecondRow },
  { id: "sections-blog-sections-01-three-column", category: "sections / blog-sections", label: "01-three-column", Component: SectionsBlogSectionsN01ThreeColumn },
  { id: "sections-blog-sections-02-three-column-with-images", category: "sections / blog-sections", label: "02-three-column-with-images", Component: SectionsBlogSectionsN02ThreeColumnWithImages },
  { id: "sections-blog-sections-03-three-column-with-background-images", category: "sections / blog-sections", label: "03-three-column-with-background-images", Component: SectionsBlogSectionsN03ThreeColumnWithBackgroundImages },
  { id: "sections-blog-sections-04-single-column", category: "sections / blog-sections", label: "04-single-column", Component: SectionsBlogSectionsN04SingleColumn },
  { id: "sections-blog-sections-05-single-column-with-images", category: "sections / blog-sections", label: "05-single-column-with-images", Component: SectionsBlogSectionsN05SingleColumnWithImages },
  { id: "sections-blog-sections-06-with-featured-post", category: "sections / blog-sections", label: "06-with-featured-post", Component: SectionsBlogSectionsN06WithFeaturedPost },
  { id: "sections-blog-sections-07-with-photo-and-list", category: "sections / blog-sections", label: "07-with-photo-and-list", Component: SectionsBlogSectionsN07WithPhotoAndList },
  { id: "sections-contact-sections-01-centered", category: "sections / contact-sections", label: "01-centered", Component: SectionsContactSectionsN01Centered },
  { id: "sections-contact-sections-02-side-by-side-grid", category: "sections / contact-sections", label: "02-side-by-side-grid", Component: SectionsContactSectionsN02SideBySideGrid },
  { id: "sections-contact-sections-03-split-with-pattern", category: "sections / contact-sections", label: "03-split-with-pattern", Component: SectionsContactSectionsN03SplitWithPattern },
  { id: "sections-contact-sections-05-simple-four-column", category: "sections / contact-sections", label: "05-simple-four-column", Component: SectionsContactSectionsN05SimpleFourColumn },
  { id: "sections-contact-sections-06-simple-centered", category: "sections / contact-sections", label: "06-simple-centered", Component: SectionsContactSectionsN06SimpleCentered },
  { id: "sections-contact-sections-07-with-testimonial", category: "sections / contact-sections", label: "07-with-testimonial", Component: SectionsContactSectionsN07WithTestimonial },
  { id: "sections-contact-sections-08-split-with-image", category: "sections / contact-sections", label: "08-split-with-image", Component: SectionsContactSectionsN08SplitWithImage },
  { id: "sections-content-sections-01-with-sticky-product-screenshot", category: "sections / content-sections", label: "01-with-sticky-product-screenshot", Component: SectionsContentSectionsN01WithStickyProductScreenshot },
  { id: "sections-content-sections-02-with-testimonial", category: "sections / content-sections", label: "02-with-testimonial", Component: SectionsContentSectionsN02WithTestimonial },
  { id: "sections-content-sections-03-with-image-tiles", category: "sections / content-sections", label: "03-with-image-tiles", Component: SectionsContentSectionsN03WithImageTiles },
  { id: "sections-content-sections-04-two-columns-with-screenshot", category: "sections / content-sections", label: "04-two-columns-with-screenshot", Component: SectionsContentSectionsN04TwoColumnsWithScreenshot },
  { id: "sections-content-sections-05-with-testimonial-and-stats", category: "sections / content-sections", label: "05-with-testimonial-and-stats", Component: SectionsContentSectionsN05WithTestimonialAndStats },
  { id: "sections-content-sections-06-split-with-image", category: "sections / content-sections", label: "06-split-with-image", Component: SectionsContentSectionsN06SplitWithImage },
  { id: "sections-content-sections-07-centered", category: "sections / content-sections", label: "07-centered", Component: SectionsContentSectionsN07Centered },
  { id: "sections-cta-sections-01-dark-panel-with-app-screenshot", category: "sections / cta-sections", label: "01-dark-panel-with-app-screenshot", Component: SectionsCtaSectionsN01DarkPanelWithAppScreenshot },
  { id: "sections-cta-sections-02-simple-stacked", category: "sections / cta-sections", label: "02-simple-stacked", Component: SectionsCtaSectionsN02SimpleStacked },
  { id: "sections-cta-sections-03-centered-on-dark-panel", category: "sections / cta-sections", label: "03-centered-on-dark-panel", Component: SectionsCtaSectionsN03CenteredOnDarkPanel },
  { id: "sections-cta-sections-04-simple-centered", category: "sections / cta-sections", label: "04-simple-centered", Component: SectionsCtaSectionsN04SimpleCentered },
  { id: "sections-cta-sections-05-simple-centered-with-gradient", category: "sections / cta-sections", label: "05-simple-centered-with-gradient", Component: SectionsCtaSectionsN05SimpleCenteredWithGradient },
  { id: "sections-cta-sections-06-simple-centered-on-brand", category: "sections / cta-sections", label: "06-simple-centered-on-brand", Component: SectionsCtaSectionsN06SimpleCenteredOnBrand },
  { id: "sections-cta-sections-07-simple-justified", category: "sections / cta-sections", label: "07-simple-justified", Component: SectionsCtaSectionsN07SimpleJustified },
  { id: "sections-cta-sections-08-simple-justified-on-subtle-brand", category: "sections / cta-sections", label: "08-simple-justified-on-subtle-brand", Component: SectionsCtaSectionsN08SimpleJustifiedOnSubtleBrand },
  { id: "sections-cta-sections-09-split-with-image", category: "sections / cta-sections", label: "09-split-with-image", Component: SectionsCtaSectionsN09SplitWithImage },
  { id: "sections-cta-sections-10-two-columns-with-photo", category: "sections / cta-sections", label: "10-two-columns-with-photo", Component: SectionsCtaSectionsN10TwoColumnsWithPhoto },
  { id: "sections-cta-sections-11-with-image-tiles", category: "sections / cta-sections", label: "11-with-image-tiles", Component: SectionsCtaSectionsN11WithImageTiles },
  { id: "sections-faq-sections-01-offset-with-supporting-text", category: "sections / faq-sections", label: "01-offset-with-supporting-text", Component: SectionsFaqSectionsN01OffsetWithSupportingText },
  { id: "sections-faq-sections-02-centered-accordion", category: "sections / faq-sections", label: "02-centered-accordion", Component: SectionsFaqSectionsN02CenteredAccordion },
  { id: "sections-faq-sections-04-side-by-side", category: "sections / faq-sections", label: "04-side-by-side", Component: SectionsFaqSectionsN04SideBySide },
  { id: "sections-faq-sections-05-three-columns", category: "sections / faq-sections", label: "05-three-columns", Component: SectionsFaqSectionsN05ThreeColumns },
  { id: "sections-faq-sections-07-three-columns-with-centered-introduction", category: "sections / faq-sections", label: "07-three-columns-with-centered-introduction", Component: SectionsFaqSectionsN07ThreeColumnsWithCenteredIntroduction },
  { id: "sections-faq-sections-08-two-columns", category: "sections / faq-sections", label: "08-two-columns", Component: SectionsFaqSectionsN08TwoColumns },
  { id: "sections-faq-sections-10-two-columns-with-centered-introduction", category: "sections / faq-sections", label: "10-two-columns-with-centered-introduction", Component: SectionsFaqSectionsN10TwoColumnsWithCenteredIntroduction },
  { id: "sections-feature-sections-01.with-product-screenshot", category: "sections / feature-sections", label: "01.with-product-screenshot", Component: SectionsFeatureSectionsN01WithProductScreenshot },
  { id: "sections-feature-sections-03.with-large-screenshot", category: "sections / feature-sections", label: "03.with-large-screenshot", Component: SectionsFeatureSectionsN03WithLargeScreenshot },
  { id: "sections-feature-sections-05.with-large-bordered-screenshot", category: "sections / feature-sections", label: "05.with-large-bordered-screenshot", Component: SectionsFeatureSectionsN05WithLargeBorderedScreenshot },
  { id: "sections-feature-sections-07.simple-three-column-with-small-icons", category: "sections / feature-sections", label: "07.simple-three-column-with-small-icons", Component: SectionsFeatureSectionsN07SimpleThreeColumnWithSmallIcons },
  { id: "sections-feature-sections-09.with-product-screenshot-on-left", category: "sections / feature-sections", label: "09.with-product-screenshot-on-left", Component: SectionsFeatureSectionsN09WithProductScreenshotOnLeft },
  { id: "sections-feature-sections-10.simple-three-column-with-large-icons", category: "sections / feature-sections", label: "10.simple-three-column-with-large-icons", Component: SectionsFeatureSectionsN10SimpleThreeColumnWithLargeIcons },
  { id: "sections-feature-sections-12.contained-in-panel", category: "sections / feature-sections", label: "12.contained-in-panel", Component: SectionsFeatureSectionsN12ContainedInPanel },
  { id: "sections-feature-sections-13.with-product-screenshot-panel", category: "sections / feature-sections", label: "13.with-product-screenshot-panel", Component: SectionsFeatureSectionsN13WithProductScreenshotPanel },
  { id: "sections-feature-sections-14.with-testimonial", category: "sections / feature-sections", label: "14.with-testimonial", Component: SectionsFeatureSectionsN14WithTestimonial },
  { id: "sections-feature-sections-15.offset-2x2-grid", category: "sections / feature-sections", label: "15.offset-2x2-grid", Component: SectionsFeatureSectionsN15Offset2x2Grid },
  { id: "sections-feature-sections-16.with-code-example-panel", category: "sections / feature-sections", label: "16.with-code-example-panel", Component: SectionsFeatureSectionsN16WithCodeExamplePanel },
  { id: "sections-feature-sections-17.offset-with-feature-list", category: "sections / feature-sections", label: "17.offset-with-feature-list", Component: SectionsFeatureSectionsN17OffsetWithFeatureList },
  { id: "sections-feature-sections-18.simple", category: "sections / feature-sections", label: "18.simple", Component: SectionsFeatureSectionsN18Simple },
  { id: "sections-feature-sections-19.centered-2x2-grid", category: "sections / feature-sections", label: "19.centered-2x2-grid", Component: SectionsFeatureSectionsN19Centered2x2Grid },
  { id: "sections-feature-sections-20.simple-3x2-grid", category: "sections / feature-sections", label: "20.simple-3x2-grid", Component: SectionsFeatureSectionsN20Simple3x2Grid },
  { id: "sections-footers-02-4-column-with-company-mission", category: "sections / footers", label: "02-4-column-with-company-mission", Component: SectionsFootersN02N4ColumnWithCompanyMission },
  { id: "sections-footers-04-4-column-with-call-to-action", category: "sections / footers", label: "04-4-column-with-call-to-action", Component: SectionsFootersN04N4ColumnWithCallToAction },
  { id: "sections-footers-06-4-column-simple", category: "sections / footers", label: "06-4-column-simple", Component: SectionsFootersN06N4ColumnSimple },
  { id: "sections-footers-08-4-column-with-newsletter", category: "sections / footers", label: "08-4-column-with-newsletter", Component: SectionsFootersN08N4ColumnWithNewsletter },
  { id: "sections-footers-10-4-column-with-newsletter-below", category: "sections / footers", label: "10-4-column-with-newsletter-below", Component: SectionsFootersN10N4ColumnWithNewsletterBelow },
  { id: "sections-footers-12-simple-centered", category: "sections / footers", label: "12-simple-centered", Component: SectionsFootersN12SimpleCentered },
  { id: "sections-footers-14-simple-with-social-links", category: "sections / footers", label: "14-simple-with-social-links", Component: SectionsFootersN14SimpleWithSocialLinks },
  { id: "sections-header-01-with-stats", category: "sections / header", label: "01-with-stats", Component: SectionsHeaderN01WithStats },
  { id: "sections-header-02-centered", category: "sections / header", label: "02-centered", Component: SectionsHeaderN02Centered },
  { id: "sections-header-03-centered-with-eyebrow", category: "sections / header", label: "03-centered-with-eyebrow", Component: SectionsHeaderN03CenteredWithEyebrow },
  { id: "sections-header-04-with-cards", category: "sections / header", label: "04-with-cards", Component: SectionsHeaderN04WithCards },
  { id: "sections-header-05-simple", category: "sections / header", label: "05-simple", Component: SectionsHeaderN05Simple },
  { id: "sections-header-06-simple-with-eyebrow", category: "sections / header", label: "06-simple-with-eyebrow", Component: SectionsHeaderN06SimpleWithEyebrow },
  { id: "sections-header-07-simple-with-background-image", category: "sections / header", label: "07-simple-with-background-image", Component: SectionsHeaderN07SimpleWithBackgroundImage },
  { id: "sections-header-08-centered-with-background-image", category: "sections / header", label: "08-centered-with-background-image", Component: SectionsHeaderN08CenteredWithBackgroundImage },
  { id: "sections-heroes-01-simple-centered", category: "sections / heroes", label: "01-simple-centered", Component: SectionsHeroesN01SimpleCentered },
  { id: "sections-heroes-02-split-with-screenshot", category: "sections / heroes", label: "02-split-with-screenshot", Component: SectionsHeroesN02SplitWithScreenshot },
  { id: "sections-heroes-03-split-with-bordered-screenshot", category: "sections / heroes", label: "03-split-with-bordered-screenshot", Component: SectionsHeroesN03SplitWithBorderedScreenshot },
  { id: "sections-heroes-04-split-with-code-example", category: "sections / heroes", label: "04-split-with-code-example", Component: SectionsHeroesN04SplitWithCodeExample },
  { id: "sections-heroes-05-simple-centered-with-background-image", category: "sections / heroes", label: "05-simple-centered-with-background-image", Component: SectionsHeroesN05SimpleCenteredWithBackgroundImage },
  { id: "sections-heroes-06-with-bordered-app-screenshot", category: "sections / heroes", label: "06-with-bordered-app-screenshot", Component: SectionsHeroesN06WithBorderedAppScreenshot },
  { id: "sections-heroes-07-with-app-screenshot", category: "sections / heroes", label: "07-with-app-screenshot", Component: SectionsHeroesN07WithAppScreenshot },
  { id: "sections-heroes-08-with-phone-mockup", category: "sections / heroes", label: "08-with-phone-mockup", Component: SectionsHeroesN08WithPhoneMockup },
  { id: "sections-heroes-09-split-with-image", category: "sections / heroes", label: "09-split-with-image", Component: SectionsHeroesN09SplitWithImage },
  { id: "sections-heroes-10-with-angled-image-on-right", category: "sections / heroes", label: "10-with-angled-image-on-right", Component: SectionsHeroesN10WithAngledImageOnRight },
  { id: "sections-heroes-11-with-image-tiles", category: "sections / heroes", label: "11-with-image-tiles", Component: SectionsHeroesN11WithImageTiles },
  { id: "sections-heroes-12-with-offset-image", category: "sections / heroes", label: "12-with-offset-image", Component: SectionsHeroesN12WithOffsetImage },
  { id: "sections-logo-clouds-01-simple-with-heading", category: "sections / logo-clouds", label: "01-simple-with-heading", Component: SectionsLogoCloudsN01SimpleWithHeading },
  { id: "sections-logo-clouds-03-simple-with-call-to-action", category: "sections / logo-clouds", label: "03-simple-with-call-to-action", Component: SectionsLogoCloudsN03SimpleWithCallToAction },
  { id: "sections-logo-clouds-05-simple-left-aligned", category: "sections / logo-clouds", label: "05-simple-left-aligned", Component: SectionsLogoCloudsN05SimpleLeftAligned },
  { id: "sections-logo-clouds-07-split-with-logos-on-right", category: "sections / logo-clouds", label: "07-split-with-logos-on-right", Component: SectionsLogoCloudsN07SplitWithLogosOnRight },
  { id: "sections-logo-clouds-09-simple", category: "sections / logo-clouds", label: "09-simple", Component: SectionsLogoCloudsN09Simple },
  { id: "sections-logo-clouds-11-grid", category: "sections / logo-clouds", label: "11-grid", Component: SectionsLogoCloudsN11Grid },
  { id: "sections-newsletter-sections-01-side-by-side-with-details", category: "sections / newsletter-sections", label: "01-side-by-side-with-details", Component: SectionsNewsletterSectionsN01SideBySideWithDetails },
  { id: "sections-newsletter-sections-02-simple-side-by-side", category: "sections / newsletter-sections", label: "02-simple-side-by-side", Component: SectionsNewsletterSectionsN02SimpleSideBySide },
  { id: "sections-newsletter-sections-04-simple-side-by-side-on-brand", category: "sections / newsletter-sections", label: "04-simple-side-by-side-on-brand", Component: SectionsNewsletterSectionsN04SimpleSideBySideOnBrand },
  { id: "sections-newsletter-sections-05-simple-stacked", category: "sections / newsletter-sections", label: "05-simple-stacked", Component: SectionsNewsletterSectionsN05SimpleStacked },
  { id: "sections-newsletter-sections-06-centered-card", category: "sections / newsletter-sections", label: "06-centered-card", Component: SectionsNewsletterSectionsN06CenteredCard },
  { id: "sections-newsletter-sections-07-side-by-side-on-card", category: "sections / newsletter-sections", label: "07-side-by-side-on-card", Component: SectionsNewsletterSectionsN07SideBySideOnCard },
  { id: "sections-pricing-01-two-tiers-with-emphasized-right-tier", category: "sections / pricing", label: "01-two-tiers-with-emphasized-right-tier", Component: SectionsPricingN01TwoTiersWithEmphasizedRightTier },
  { id: "sections-pricing-02-two-tiers-with-emphasized-left-tier", category: "sections / pricing", label: "02-two-tiers-with-emphasized-left-tier", Component: SectionsPricingN02TwoTiersWithEmphasizedLeftTier },
  { id: "sections-pricing-03-three-tiers-with-logos-and-feature-comparison", category: "sections / pricing", label: "03-three-tiers-with-logos-and-feature-comparison", Component: SectionsPricingN03ThreeTiersWithLogosAndFeatureComparison },
  { id: "sections-pricing-04-two-tiers-with-extra-tier", category: "sections / pricing", label: "04-two-tiers-with-extra-tier", Component: SectionsPricingN04TwoTiersWithExtraTier },
  { id: "sections-pricing-05-single-price-with-details", category: "sections / pricing", label: "05-single-price-with-details", Component: SectionsPricingN05SinglePriceWithDetails },
  { id: "sections-pricing-06-three-tiers", category: "sections / pricing", label: "06-three-tiers", Component: SectionsPricingN06ThreeTiers },
  { id: "sections-pricing-07-three-tiers-with-dividers", category: "sections / pricing", label: "07-three-tiers-with-dividers", Component: SectionsPricingN07ThreeTiersWithDividers },
  { id: "sections-pricing-08-three-tiers-with-emphasized-tier", category: "sections / pricing", label: "08-three-tiers-with-emphasized-tier", Component: SectionsPricingN08ThreeTiersWithEmphasizedTier },
  { id: "sections-pricing-09-three-tiers-with-toggle", category: "sections / pricing", label: "09-three-tiers-with-toggle", Component: SectionsPricingN09ThreeTiersWithToggle },
  { id: "sections-pricing-11-four-tiers-with-toggle", category: "sections / pricing", label: "11-four-tiers-with-toggle", Component: SectionsPricingN11FourTiersWithToggle },
  { id: "sections-pricing-12-with-comparison-table", category: "sections / pricing", label: "12-with-comparison-table", Component: SectionsPricingN12WithComparisonTable },
  { id: "sections-pricing-14-three-tiers-with-feature-comparison", category: "sections / pricing", label: "14-three-tiers-with-feature-comparison", Component: SectionsPricingN14ThreeTiersWithFeatureComparison },
  { id: "sections-stats-sections-01-simple", category: "sections / stats-sections", label: "01-simple", Component: SectionsStatsSectionsN01Simple },
  { id: "sections-stats-sections-03-simple-grid", category: "sections / stats-sections", label: "03-simple-grid", Component: SectionsStatsSectionsN03SimpleGrid },
  { id: "sections-stats-sections-05-with-background-image", category: "sections / stats-sections", label: "05-with-background-image", Component: SectionsStatsSectionsN05WithBackgroundImage },
  { id: "sections-stats-sections-06-split-with-image", category: "sections / stats-sections", label: "06-split-with-image", Component: SectionsStatsSectionsN06SplitWithImage },
  { id: "sections-stats-sections-07-timeline", category: "sections / stats-sections", label: "07-timeline", Component: SectionsStatsSectionsN07Timeline },
  { id: "sections-stats-sections-08-stepped", category: "sections / stats-sections", label: "08-stepped", Component: SectionsStatsSectionsN08Stepped },
  { id: "sections-stats-sections-09-two-column-description", category: "sections / stats-sections", label: "09-two-column-description", Component: SectionsStatsSectionsN09TwoColumnDescription },
  { id: "sections-stats-sections-10-with-description", category: "sections / stats-sections", label: "10-with-description", Component: SectionsStatsSectionsN10WithDescription },
  { id: "sections-team-sections-01-small-images", category: "sections / team-sections", label: "01-small-images", Component: SectionsTeamSectionsN01SmallImages },
  { id: "sections-team-sections-02-large-images", category: "sections / team-sections", label: "02-large-images", Component: SectionsTeamSectionsN02LargeImages },
  { id: "sections-team-sections-03-grid-with-round-images", category: "sections / team-sections", label: "03-grid-with-round-images", Component: SectionsTeamSectionsN03GridWithRoundImages },
  { id: "sections-team-sections-04-large-grid-with-cards", category: "sections / team-sections", label: "04-large-grid-with-cards", Component: SectionsTeamSectionsN04LargeGridWithCards },
  { id: "sections-team-sections-05-with-image-and-short-paragraph", category: "sections / team-sections", label: "05-with-image-and-short-paragraph", Component: SectionsTeamSectionsN05WithImageAndShortParagraph },
  { id: "sections-team-sections-06-with-vertical-images", category: "sections / team-sections", label: "06-with-vertical-images", Component: SectionsTeamSectionsN06WithVerticalImages },
  { id: "sections-team-sections-07-with-vertical-images-full-width", category: "sections / team-sections", label: "07-with-vertical-images-full-width", Component: SectionsTeamSectionsN07WithVerticalImagesFullWidth },
  { id: "sections-team-sections-08-grid-with-large-round-images", category: "sections / team-sections", label: "08-grid-with-large-round-images", Component: SectionsTeamSectionsN08GridWithLargeRoundImages },
  { id: "sections-team-sections-09-medium-images", category: "sections / team-sections", label: "09-medium-images", Component: SectionsTeamSectionsN09MediumImages },
  { id: "sections-testimonials-02-simple-centered", category: "sections / testimonials", label: "02-simple-centered", Component: SectionsTestimonialsN02SimpleCentered },
  { id: "sections-testimonials-03-with-large-avatar", category: "sections / testimonials", label: "03-with-large-avatar", Component: SectionsTestimonialsN03WithLargeAvatar },
  { id: "sections-testimonials-04-with-overlapping-image", category: "sections / testimonials", label: "04-with-overlapping-image", Component: SectionsTestimonialsN04WithOverlappingImage },
  { id: "sections-testimonials-05-with-background-image", category: "sections / testimonials", label: "05-with-background-image", Component: SectionsTestimonialsN05WithBackgroundImage },
  { id: "sections-testimonials-06-side-by-side", category: "sections / testimonials", label: "06-side-by-side", Component: SectionsTestimonialsN06SideBySide },
  { id: "sections-testimonials-08-with-star-rating", category: "sections / testimonials", label: "08-with-star-rating", Component: SectionsTestimonialsN08WithStarRating },
  { id: "sections-testimonials-09-grid", category: "sections / testimonials", label: "09-grid", Component: SectionsTestimonialsN09Grid },
  { id: "sections-testimonials-10-subtle-grid", category: "sections / testimonials", label: "10-subtle-grid", Component: SectionsTestimonialsN10SubtleGrid },
];
